visual_studio/rift_estacionamento/rift_estacionamento/rift_estacionamento/Controllers/PessoasJuridicasController.cs
using rift_estacionamento.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using System;

namespace rift_estacionamento.Controllers
{
    [Authorize]
    public class PessoasJuridicasController : Controller
    {
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult FonesPessoaJuridica(int id_pessoa_juridica, string razao_social, string responseStr, string responseStrFonePJ, string responseStatusCode)
        {

            FonePessoaJuridica _fones_pessoa_juridica = new FonePessoaJuridica();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                var settings = new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore
                };
                _fones_pessoa_juridica = JsonConvert.DeserializeObject<FonePessoaJuridica>(responseStr, settings);
            }

            ProcessarRegistro _processarregistro = new ProcessarRegistro();

            if (!string.IsNullOrWhiteSpace(responseStrFonePJ))
            {
                _processarregistro = JsonConvert.DeserializeObject<ProcessarRegistro>(responseStrFonePJ);
            }


            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.id_pessoa_juridica = id_pessoa_juridica;
            ViewBag.razao_social = razao_social;

            ViewBag.fones_pj = (_fones_pessoa_juridica == null || _fones_pessoa_juridica.Item1 == null) ? new List<FonePessoaJuridica.Dados>() : _fones_pessoa_juridica.Item1;

            ViewBag.erro = (_processarregistro == null || _processarregistro.Item2 == null ? false : _processarregistro.Item2.Erro);
            ViewBag.linhasafetadas = (_processarregistro == null || _processarregistro.Item1 == null ? -1 : _processarregistro.Item1.Linhasafetadas);
            ViewBag.mensagem = (_processarregistro == null || _processarregistro.Item2 == null ? "" : _processarregistro.Item2.Mensagem);
            ViewBag.responseStatusCode = responseStatusCode;

            return View("FonesPessoaJuridica");
        }

        public IActionResult EmailsPessoaJuridica(int id_pessoa_juridica, string razao_social, string responseStr, string responseStrEmailPJ, string responseStatusCode)
        {

            EmailPessoaJuridica _emails_pessoa_juridica = new EmailPessoaJuridica();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                var settings = new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore
                };
                _emails_pessoa_juridica = JsonConvert.DeserializeObject<EmailPessoaJuridica>(responseStr, settings);
            }

            ProcessarRegistro _processarregistro = new ProcessarRegistro();

            if (!string.IsNullOrWhiteSpace(responseStrEmailPJ))
            {
                _processarregistro = JsonConvert.DeserializeObject<ProcessarRegistro>(responseStrEmailPJ);
            }


            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.id_pessoa_juridica = id_pessoa_juridica;
            ViewBag.razao_social = razao_social;

            ViewBag.emails_pj = (_emails_pessoa_juridica == null || _emails_pessoa_juridica.Item1 == null) ? new List<EmailPessoaJuridica.Dados>() : _emails_pessoa_juridica.Item1;

            ViewBag.erro = (_processarregistro == null || _processarregistro.Item2 == null ? false : _processarregistro.Item2.Erro);
            ViewBag.linhasafetadas = (_processarregistro == null || _processarregistro.Item1 == null ? -1 : _processarregistro.Item1.Linhasafetadas);
            ViewBag.mensagem = (_processarregistro == null || _processarregistro.Item2 == null ? "" : _processarregistro.Item2.Mensagem);
            ViewBag.responseStatusCode = responseStatusCode;

            return View("EmailsPessoaJuridica");
        }

        public IActionResult EditarPessoasJuridicas(int id, string responseStr, string responseStatusCode)
        {

            ProcessarRegistro _processarregistro = new ProcessarRegistro();
            PessoaJuridica _pessoajuridica = new PessoaJuridica();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                if (id == 0)
                {
                    _processarregistro = JsonConvert.DeserializeObject<ProcessarRegistro>(responseStr);
                }
                else
                {
                    _pessoajuridica = JsonConvert.DeserializeObject<PessoaJuridica>(responseStr);
                }
            }


            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.id = id;
            ViewBag.cnpj = (_pessoajuridica == null || _pessoajuridica.Item1 == null) ? "" : _pessoajuridica.Item1[0].Cnpj;
            ViewBag.razao_social = (_pessoajuridica == null || _pessoajuridica.Item1 == null) ? "" : _pessoajuridica.Item1[0].Razao_social;
            ViewBag.fantasia = (_pessoajuridica == null || _pessoajuridica.Item1 == null) ? "" : _pessoajuridica.Item1[0].Fantasia;
            ViewBag.endereco = (_pessoajuridica == null || _pessoajuridica.Item1 == null) ? "" : _pessoajuridica.Item1[0].Endereco;

            ViewBag.erro = (_processarregistro == null || _processarregistro.Item2 == null ? false : _processarregistro.Item2.Erro);
            ViewBag.linhasafetadas = (_processarregistro == null || _processarregistro.Item1 == null ? -1 : _processarregistro.Item1.Linhasafetadas);
            ViewBag.mensagem = (_processarregistro == null || _processarregistro.Item2 == null ? "" : _processarregistro.Item2.Mensagem);
            ViewBag.responseStatusCode = responseStatusCode;

            return View("EditarPessoasJuridicas");
        }


        public IActionResult IncluirPessoasJuridicas(string responseStr, string responseStatusCode, string inclusao_pessoajuridica)
        {
            NovoRegistro _novapessofisica = new NovoRegistro();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                _novapessofisica = JsonConvert.DeserializeObject<NovoRegistro>(responseStr);
            }

            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.id = (_novapessofisica == null || _novapessofisica.Item1 == null ? 0 : _novapessofisica.Item1.Id);
            ViewBag.erro = (_novapessofisica == null  || _novapessofisica.Item2 == null ? false : _novapessofisica.Item2.Erro);
            ViewBag.mensagem = (_novapessofisica == null || _novapessofisica.Item2 == null ? "" : _novapessofisica.Item2.Mensagem);
            ViewBag.responseStatusCode = responseStatusCode;

            if (ViewBag.erro)
            {
                Dictionary<string, string> inclusao = JsonConvert.DeserializeObject<Dictionary<string, string>>(inclusao_pessoajuridica);
                ViewBag.cnpj = inclusao["cnpj"];
                ViewBag.razao_social = inclusao["razao_social"];
                ViewBag.fantasia = inclusao["fantasia"];
                ViewBag.endereco = inclusao["endereco"];
            }

            return View("IncluirPessoasJuridicas");
        }

        public IActionResult ConsultarPessoasJuridicas(string responseStr, string responseStrExc, string responseStatusCode)
        {
            PessoaJuridica _pessoajuridica = new PessoaJuridica();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                _pessoajuridica = JsonConvert.DeserializeObject<PessoaJuridica>(responseStr);
                ViewBag.erro = (_pessoajuridica == null || _pessoajuridica.Item2 == null ? false : _pessoajuridica.Item2.Erro);
                ViewBag.mensagem = (_pessoajuridica == null || _pessoajuridica.Item2 == null ? "" : _pessoajuridica.Item2.Mensagem);
                ViewBag.excluindo = false;
            }

            if (!string.IsNullOrWhiteSpace(responseStrExc))
            {
                ProcessarRegistro _proc = new ProcessarRegistro();
                _proc = JsonConvert.DeserializeObject<ProcessarRegistro>(responseStrExc);
                ViewBag.erro = (_proc == null || _proc.Item2 == null ? false : _proc.Item2.Erro);
                ViewBag.mensagem = (_proc == null || _proc.Item2 == null ? "" : _proc.Item2.Mensagem);
                ViewBag.excluindo = true;
            }

          
            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.pessoasjuridicas = (_pessoajuridica == null || _pessoajuridica.Item1 == null) ? new List<PessoaJuridica.Dados>() : _pessoajuridica.Item1;

            ViewBag.responseStatusCode = responseStatusCode;

            return View("ConsultarPessoasJuridicas");
        }


        [HttpPost]
        public async Task<IActionResult>IncluirPessoasJuridicasPost( string cnpj, string razao_social, string fantasia, string endereco)
        {
            ReClienteHttp httpClient = ReClienteHttp.Instance;

            var novo_pessoajuridica = new Dictionary<string, string>
            {
                { "cnpj", cnpj },
                { "razao_social", razao_social },
                { "fantasia", fantasia },
                { "endereco", endereco },
                { "token", Request.Cookies[Constantes.TOKEN_USUARIO] }
            };

            var request = new HttpRequestMessage();
            request.Content = new FormUrlEncodedContent(novo_pessoajuridica);

            var response = httpClient.client.PostAsync("api/incluir_pessoa_juridica", request.Content).Result;

            string responseStr = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {

visual_studio/rift_estacionamento/rift_estacionamento/rift_estacionamento/Views/PessoasJuridicas/ConsultarPessoasJuridicas.cshtml
@{
    ViewData["Title"] = "ConsultarPessoasJuridicas";
}

<div style="padding-left: 5%; padding-top: 1%; padding-right: 5%">
    <div>
        <a id="fechar" asp-controller="Home" asp-action="Index"> <img style="width: 28px;" src="~/images/fechar.svg" /></a>
        <h2>Consultar Pessoas Jurídicas<img style="width: 28px;" src="~/images/loader.gif" id="loaderImg" hidden></h2>
    </div>
    <hr />
    <form asp-controller="PessoasJuridicas" asp-action="ConsultarPessoasJuridicasPost" method="post" onsubmit="disableObj(ConsultarBtn);showObj(loaderImg)">
        <table id="formularios">
            <tr>
                <th>
                    <label for="id">Código</label>
                    <br />
                    <input class="input input-sm" id="id" name="id" type="number" />
                </th>
                <th>
                    <label for="cnpj">CNPJ</label>
                    <br />
                    <input class="input input-sm" id="cnpj" name="cnpj" type="text" />
                </th>
                <th>
                    <label for="razao_social">Razão Social</label>
                    <br />
                    <input class="input input-sm" id="razao_social" name="razao_social" type="text" />
                </th>
                <th>
                    <label for="descricao">Nome Fantasia</label>
                    <br />
                    <input class="input input-sm" id="fantasia" name="fantasia" type="text" />
                </th>
            </tr>
            <tr>
        </table>
        <table id="formularios">
            <tr>
                <th>
                    <button class="btn btn-default" id="ConsultarBtn" type="submit">Consultar</button>
                </th>
            </tr>
        </table>
    </form>
    <hr />
    <table id="consultas">
        <tr>
            <th width="50">Cód.</th>
            <th width="150">CNPJ</th>
            <th width="250">Razao Social</th>
            <th width="80">Fantasia</th>
            <th width="300">Endereço</th>
            <th width="280">Telefones</th>
            <th width="280">E-mails</th>
            <th width="200">Ação</th>
        </tr>
        @foreach (var pessoajuridica in ViewBag.pessoasjuridicas)
        {
            <tr>
                <td>@pessoajuridica.Id</td>
                <td>@pessoajuridica.Cnpj</td>
                <td>@pessoajuridica.Razao_social</td>
                <td>@pessoajuridica.Fantasia</td>
                <td>@pessoajuridica.Endereco</td>
                <td>@pessoajuridica.Fones</td>
                <td>@pessoajuridica.Emails</td>

                <td>
                    <a asp-area="" asp-controller="PessoasJuridicas" asp-action="AcaoEditarPessoasJuridicas" asp-route-id="@pessoajuridica.Id"><img style="margin: 2px; width: 32px;" title="Editar pessoa física" src="~/images/editar.svg"></a>
                    <a asp-area="" asp-controller="PessoasJuridicas" asp-action="AcaoFonesPessoaJuridica" asp-route-id_pessoa_juridica="@pessoajuridica.Id" asp-route-razao_social="@pessoajuridica.Razao_social"><img style="margin: 2px; width: 26px;" title="Telefones" src="~/images/fone.svg"></a>
                    <a asp-area="" asp-controller="PessoasJuridicas" asp-action="AcaoEmailsPessoaJuridica" asp-route-id_pessoa_juridica="@pessoajuridica.Id" asp-route-razao_social="@pessoajuridica.Razao_social"><img style="margin: 2px; width: 26px;" title="E-mails" src="~/images/email.svg"></a>
                    <a asp-area="" asp-controller="PessoasJuridicas" asp-action="ExcluirPessoasJuridicas" asp-route-id="@pessoajuridica.Id" onclick=" return Confirmar('Excluir pessoa jurídica?')"><img style="margin: 2px; width: 32px;" title="Excluir pessoa jurídica" src="~/images/excluir.svg"></a>
                </td>
            </tr>
        }
    </table>
    @if (ViewBag.responseStatusCode == "OK")
    {
        @if (ViewBag.erro || (ViewBag.linhasafetadas == 0 && ViewBag.excluindo))
        {
            <h4 style="color : red">@ViewBag.mensagem</h4>
        }
        else
        {
            @if (ViewBag.excluindo)
            {
                <h4 style="color : green">pessoa jurídica excluída.</h4>
            }
            else
            {
                @if (ViewBag.pessoasjuridicas.Count == 0)
                {
                    <h5 style="color : red">Nenhum registro encontrado.</h5>
                }
            }

        }
    }
    else
    {
        <h4 style="color : red"> @ViewBag.responseStatusCode </h4>
    }
</div>

visual_studio/rift_estacionamento/rift_estacionamento/rift_estacionamento/Views/PessoasJuridicas/EditarPessoasJuridicas.cshtml
@{
    ViewData["Title"] = "EditarPessoasJuridicas";
}

<div style="padding-left: 5%; padding-top: 1%; padding-right: 5%">
    <div>
        <a id="fechar" asp-controller="Home" asp-action="Index"> <img style="width: 28px;" src="~/images/fechar.svg" /></a>
        <h2>Editar Pessoa Jurídica <img style="width: 28px;" src="~/images/loader.gif" id="loaderImg" hidden></h2>
    </div>
    <hr />
    @if (@ViewBag.id != 0)
    {
        <form asp-controller="PessoasJuridicas" asp-action="EditarPessoasJuridicasPost" method="post" onsubmit="disableObj(SalvarBtn);disableObj(CancelarBtn);showObj(loaderImg)">
            <label for="id">Código: @ViewBag.id</label>
            <input class="input input-sm" id="id" name="id" type="hidden" value="@ViewBag.id" />
            <table id="formularios">
                <tr>
                    <th>
                        <label for="cnpj">CNPJ</label>
                        <br />
                        <input class="input input-sm" id="cnpj" name="cnpj" type="text" value="@ViewBag.cnpj" />
                    </th>
                    <th>
                        <label for="razao_social">Razão Social</label>
                        <br />
                        <input class="input input-sm" id="razao_social" name="razao_social" type="text" value="@ViewBag.razao_social" />
                    </th>
                    <th>
                        <label for="fantasia">Nome Fantasia</label>
                        <br />
                        <input class="input input-sm" id="fantasia" name="fantasia" type="text" value="@ViewBag.fantasia" />
                    </th>
                    <th>
                        <label for="Endereco">Endereço</label>
                        <br />
                        <input class="input input-sm" id="Endereco" name="Endereco" type="text" value="@ViewBag.endereco" />
                    </th>
                </tr>
                <tr>
                    <th>
                        <button class="btn btn-default" id="SalvarBtn" type="submit">Salvar</button>
                        <input class="btn btn-default" id="CancelarBtn" type="button" value="Cancelar" onclick="location.href='@Url.Action("RefazerUltimaConsultaPessoaJuridica", "PessoasJuridicas")'" />
                    </th>
                </tr>
            </table>
        </form>
    }
    else
    {
        <input class="btn btn-default" type="button" value="Voltar" onclick="location.href='@Url.Action("RefazerUltimaConsultaPessoaJuridica", "PessoasJuridicas")'" />
    }
    <hr />
    @if (ViewBag.responseStatusCode == "OK")
    {
        @if (ViewBag.erro || ViewBag.linhasafetadas == 0)
        {
            <h4 style="color : red">@ViewBag.mensagem</h4>
        }
        else
        {
            @if (ViewBag.linhasafetadas >= 1)
            {
                <h4 style="color : green">Pessoa Jurídica atualizada.</h4>
            }

        }
    }
    else
    {
        <h4 style="color : red"> @ViewBag.responseStatusCode </h4>
    }
</div>

visual_studio/rift_estacionamento/rift_estacionamento/rift_estacionamento/Views/PessoasJuridicas/EmailsPessoaJuridica.cshtml
@{
    ViewData["Title"] = "EmailsPessoaJuridica";
}

<div style="padding-left: 5%; padding-top: 1%; padding-right: 5%">
    <div>
        <a id="fechar" asp-controller="Home" asp-action="Index"> <img style="width: 28px;" src="~/images/fechar.svg" /></a>
        <h2>E-mails<img style="width: 28px;" src="~/images/loader.gif" id="loaderImg" hidden></h2>
    </div>
    <hr />
    <table id="formularios">
        <tr>
            <th>
                <label for="id_pessoa_juridica">Código: @ViewBag.id_pessoa_juridica</label>
            </th>
            <th>
                <label for="razao_social">Razão Social: @ViewBag.razao_social</label>
            </th>
        </tr>
    </table>
    <hr />

    <form asp-controller="PessoasJuridicas" asp-action="IncluirEmailsPessoaJuridicaPost" method="post" onsubmit="disableObj(ExcluirBtn);disableObj(CancelarBtn);showObj(loaderImg)">
        <table>
            <tr>
                <th>
                    <input class="input input-sm" id="id_pessoa_juridica" name="id_pessoa_juridica" type="hidden" value="@ViewBag.id_pessoa_juridica" />
                    <input class="input input-sm" id="razao_social" name="razao_social" type="hidden" value="@ViewBag.razao_social" />
                    <br />
                    <label for="email">E-mail</label>
                    <br />
                    <input style="width:100%" class="input input-sm" id="email" name="email" type="text" value="@ViewBag.email" />
                </th>
            </tr>
            <tr>
                <th>
                    <br />
                    <button class="btn btn-default" id="IncluirBtn" type="submit">Incluir</button>
                    <button class="btn btn-default" id="ConsultaBtn" asp-area="" asp-controller="PessoasJuridicas" asp-action="RefazerUltimaConsultaPessoaJuridica">Voltar</button>
                </th>
            </tr>
        </table>
    </form>
    <hr />

    <table id="consultas">
        <tr>
            <th width=200>E-mail</th>
            <th width=100>Ação</th>
        </tr>
        @foreach (var email_pj in ViewBag.emails_pj)
        {
            <tr>
                <td>@email_pj.Email</td>
                <td>
                    <a asp-area="" asp-controller="PessoasJuridicas" asp-action="ExcluirEmailPessoaJuridica"
                       asp-route-id="@email_pj.Id" asp-route-id_pessoa_juridica="@ViewBag.id_pessoa_juridica" asp-route-razao_social="@ViewBag.razao_social" 
                       onclick=" return Confirmar('Excluir e-mail?')"><img style="margin: 5px; width: 32px;" title="Excluir e-mail" src="~/images/excluir.svg"></a>
                </td>
            </tr>
        }
    </table>

    @if (ViewBag.responseStatusCode == "OK")
    {
        @if (ViewBag.erro || ViewBag.linhasafetadas == 0)
        {
            <h4 style="color : red">@ViewBag.mensagem</h4>
        }
    }
    else
    {
        <h4 style="color : red"> @ViewBag.responseStatusCode </h4>
    }
</div>

visual_studio/rift_estacionamento/rift_estacionamento/rift_estacionamento/Views/PessoasJuridicas/FonesPessoaJuridica.cshtml
@{
    ViewData["Title"] = "FonesPessoaJuridica";
}

<div style="padding-left: 5%; padding-top: 1%; padding-right: 5%">
    <div>
        <a id="fechar" asp-controller="Home" asp-action="Index"> <img style="width: 28px;" src="~/images/fechar.svg" /></a>
        <h2>Telefones<img style="width: 28px;" src="~/images/loader.gif" id="loaderImg" hidden></h2>
    </div>
    <hr />
    <table id="formularios">
        <tr>
            <th>
                <label for="id_pessoa_juridica">Código: @ViewBag.id_pessoa_juridica</label>
            </th>
            <th>
                <label for="razao_social">Razão Social: @ViewBag.razao_social</label>
            </th>
        </tr>
    </table>
    <hr />

    <form asp-controller="PessoasJuridicas" asp-action="IncluirFonesPessoaJuridicaPost" method="post" onsubmit="disableObj(ExcluirBtn);disableObj(CancelarBtn);showObj(loaderImg)">
        <table>
            <tr>
                <th>
                    <input class="input input-sm" id="id_pessoa_juridica" name="id_pessoa_juridica" type="hidden" value="@ViewBag.id_pessoa_juridica" />
                    <input class="input input-sm" id="razao_social" name="razao_social" type="hidden" value="@ViewBag.razao_social" />
                    <br />
                    <label for="fone">Telefone</label>
                    <br />
                    <input style="width:100%" class="input input-sm" id="fone" name="fone" type="text" value="@ViewBag.fone" />
                </th>
            </tr>
            <tr>
                <th>
                    <br />
                    <button class="btn btn-default" id="IncluirBtn" type="submit">Incluir</button>
                    <button class="btn btn-default" id="ConsultaBtn" asp-area="" asp-controller="PessoasJuridicas" asp-action="RefazerUltimaConsultaPessoaJuridica">Voltar</button>
                </th>
            </tr>
        </table>
    </form>
    <hr />

    <table id="consultas">
        <tr>
            <th width=200>Telefone</th>
            <th width=100>Ação</th>
        </tr>
        @foreach (var fone_pj in ViewBag.fones_pj)
        {
            <tr>
                <td>@fone_pj.Fone</td>
                <td>
                    <a asp-area="" asp-controller="PessoasJuridicas" asp-action="ExcluirFonePessoaJuridica"
                       asp-route-id="@fone_pj.Id" asp-route-id_pessoa_juridica="@ViewBag.id_pessoa_juridica" asp-route-razao_social="@ViewBag.razao_social" 
                       onclick=" return Confirmar('Excluir telefone?')"><img style="margin: 5px; width: 32px;" title="Excluir telefone" src="~/images/excluir.svg"></a>
                </td>
            </tr>
        }
    </table>

    @if (ViewBag.responseStatusCode == "OK")
    {
        @if (ViewBag.erro || ViewBag.linhasafetadas == 0)
        {
            <h4 style="color : red">@ViewBag.mensagem</h4>
        }
    }
    else
    {
        <h4 style="color : red"> @ViewBag.responseStatusCode </h4>
    }
</div>

visual_studio/rift_estacionamento/rift_estacionamento/rift_estacionamento/Views/PessoasJuridicas/IncluirPessoasJuridicas.cshtml
@{
    ViewData["Title"] = "IncluirPessoasJuridicas";
}

<div style="padding-left: 5%; padding-top: 1%; padding-right: 5%">
    <div>
        <a id="fechar" asp-controller="Home" asp-action="Index"> <img style="width: 28px;" src="~/images/fechar.svg" /></a>
        <h2>Incluir Pessoa Física <img style="width: 28px;" src="~/images/loader.gif" id="loaderImg" hidden></h2>
    </div>
    <hr />


    <form asp-controller="PessoasJuridicas" asp-action="IncluirPessoasJuridicasPost" method="post" onsubmit="disableObj(IncluirBtn);showObj(loaderImg)">
        <table id="formularios">
            <tr>
                <th>
                    <label for="cnpj">CNPJ</label>
                    <br />
                    <input class="input input-sm" id="cnpj" name="cnpj" type="text" value="@ViewBag.cnpj" />
                </th>
                <th>
                    <label for="razao_social">Razão Social</label>
                    <br />
                    <input class="input input-sm" id="razao_social" name="razao_social" type="text" value="@ViewBag.razao_social" />
                </th>
                <th>
                    <label for="fantasia">Nome Fantasia</label>
                    <br />
                    <input class="input input-sm" id="fantasia" name="fantasia" type="text" value="@ViewBag.fantasia" />
                </th>
                <th>
                    <label for="Endereco">Endereço</label>
                    <br />
                    <input class="input input-sm" id="Endereco" name="Endereco" type="text" value="@ViewBag.endereco" />
                </th>
            </tr>
            <tr>
                <th>
                    <button class="btn btn-default" id="IncluirBtn" type="submit">Incluir</button>
                </th>
            </tr>
        </table>
    </form>
    <hr />
    @if (ViewBag.responseStatusCode == "OK")
    {
        @if (ViewBag.erro || ViewBag.id == 0)
        {
            <h4 style="color : red">@ViewBag.mensagem</h4>
        }
        else
        {
            <h4 style="color : green">'Pessoa Jurídica incluída. Código: @ViewBag.id</h4>
        }
    }
    else
    {
        <h4 style="color : red"> @ViewBag.responseStatusCode </h4>
    }
</div>