net_core/dw_frontoffice/Models/Base.cs
namespace dw_frontoffice.Models
{
    public class Base
    {
        public class Retorno
        {
            public bool Erro { get; set; }
            public string Mensagem { get; set; }
        }

        public Retorno Item2 { get; set; }

        public class Paginacao
        {
            public int Max_id { get; set; }
            public int Count_id { get; set; }
        }

        public Paginacao Item3 { get; set; }
    }
}

net_core/dw_frontoffice/Models/Cidade.cs
using System.Collections.Generic;

namespace dw_frontoffice.Models
{
    public class Cidade : Base
    {
        public class Dados
        {
            public int Id { get; set; }
            public string Nome { get; set; }
            public string Uf { get; set; }

            public string Name
            {
                get { return Nome + "/" + Uf; }
            }
        }

        public List<Dados> Item1 { get; set; }

    }
}

net_core/dw_frontoffice/Models/GrpProduto.cs
using System.Collections.Generic;

namespace dw_frontoffice.Models
{
    public class GrpProduto : Base
    {
        public class Dados
        {
            public int Id { get; set; }
            public string Descricao { get; set; }
            public string Icone { get; set; }
        }

        public List<Dados> Item1 { get; set; }

    }
}

net_core/dw_frontoffice/Models/NovoRegistro.cs
namespace dw_frontoffice.Models
{
    public class NovoRegistro : Base
    {
        public class Dados
        {
            public int Id { get; set; }
        }

        public Dados Item1 { get; set; }
   
    }
}

net_core/dw_frontoffice/Models/ProcessarRegistro.cs
namespace dw_frontoffice.Models
{
    public class ProcessarRegistro : Base
    {
        public class Dados
        {
            public int Linhasafetadas { get; set; }
        }

        public Dados Item1 { get; set; }

    }
}

net_core/dw_frontoffice/Models/Usuario.cs
using System.Collections.Generic;


namespace dw_frontoffice.Models
{

    public class Usuario : Base
    {
        public class Dados
        {
            private string _Cpf;

            public int Id { get; set; }
            public string Email { get; set; }
            public string Senha { get; set; }
            public string Nome { get; set; }
            public string Cpf
            {
                get { return _Cpf; }
                set { _Cpf = Utils.FormatCPF(value); }
            }
            public string Aplicativo { get; set; }
            public string Retaguarda { get; set; }
            public string Empresa { get; set; }
            public int Id_cidade_ap { get; set; }
            public string Nome_cidade_ap { get; set; }
            public int Id_situacao { get; set; }
            public string Desc_situacao { get; set; }
            public int Id_empresa { get; set; }
            public string Razao_social { get; set; }
        }

        public List<Dados> Item1 { get; set; }

    }
}

net_core/dw_frontoffice/Controllers/CidadesController.cs
using dw_frontoffice.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace dw_frontoffice.Controllers
{
    [Authorize]
    public class CidadesController : Controller
    {

        public IActionResult ConsultarCidadesAutoCompletar(string nome)
        {
            if (!string.IsNullOrWhiteSpace(nome))
            {
                DwClienteHttp httpClient = DwClienteHttp.Instance;

                string responseStr;

                var consulta_cidade = new Dictionary<string, string>
                {
                   { "nome", nome},
                   { "token", Request.Cookies[Constantes.TOKEN_USUARIO] }
                };

                var request = new HttpRequestMessage();
                request.Content = new FormUrlEncodedContent(consulta_cidade);
                HttpResponseMessage response;

                try
                {
                    response = httpClient.client.PostAsync("api/consultar_cidade", request.Content).Result;
                }
                catch
                {
                    return new JsonResult("");
                }
                

                responseStr = response.Content.ReadAsStringAsync().Result;

                if (!string.IsNullOrWhiteSpace(responseStr))
                {
                    return new JsonResult(JsonConvert.DeserializeObject<Cidade>(responseStr).Item1);
                }
                else
                {
                    return new JsonResult("");
                }
            }
            else
            {
                return new JsonResult("");
            }
        }

    }
}

net_core/dw_frontoffice/Controllers/GrpProdutosController.cs
using dw_frontoffice.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using System.Net;

namespace dw_frontoffice.Controllers
{
    [Authorize]
    public class GrpProdutosController : Controller
    {

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult ConsultarGrpProdutos(string responseStr = "", string responseStatusCode = "")
        {
            GrpProduto _grpproduto = new GrpProduto();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                _grpproduto = JsonConvert.DeserializeObject<GrpProduto>(responseStr);
                ViewBag.erro = (_grpproduto == null || _grpproduto.Item2 == null ? false : _grpproduto.Item2.Erro);
                ViewBag.mensagem = (_grpproduto == null || _grpproduto.Item2 == null ? "" : _grpproduto.Item2.Mensagem);
            }
            else
            {
                ViewBag.erro = false;
            }

            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.grpprodutos = (_grpproduto == null || _grpproduto.Item1 == null) ? new List<GrpProduto.Dados>() : _grpproduto.Item1;

            ViewBag.responseStatusCode = responseStatusCode;

            return View("ConsultarGrpProdutos");
        }

        [HttpPost]
        public async Task<IActionResult> ConsultarGrpProdutosPost(int id, string descricao)
        {
            DwClienteHttp httpClient = DwClienteHttp.Instance;

            var consulta_grpproduto = new Dictionary<string, string>
            {
                { "id", id.ToString() },
                { "descricao", descricao },
                { "id_situacao", Constantes.ATIVO.ToString() },
                { "token", Request.Cookies[Constantes.TOKEN_USUARIO] }
            };

            var request = new HttpRequestMessage();
            request.Content = new FormUrlEncodedContent(consulta_grpproduto);

            var response = httpClient.client.PostAsync("api/consultar_grp_produto", request.Content).Result;

            string responseStr = await response.Content.ReadAsStringAsync();
 
            if (response.IsSuccessStatusCode)
            {
                return ConsultarGrpProdutos(responseStr, response.StatusCode.ToString());
            }
            else
            {
                if (response.StatusCode == HttpStatusCode.Unauthorized)
                {
                    return RedirectToAction("Logout", "Auth");
                }
                else
                {
                    return RedirectToAction(nameof(Error));
                }
            }

        }

    }
}

net_core/dw_frontoffice/Views/GrpProdutos/ConsultarGrpProdutos.cshtml
@{
    ViewData["Title"] = "ConsultarGrpProdutos";
}

<div style="padding-left: 5%; padding-top: 1%; padding-right: 5%">
    <div>
        <a id="fechar" asp-controller="Home" asp-action="Index"> <img style="width: 28px;" src="~/images/fechar.svg" /></a>
        <h2>Consultar Grupos de Produtos <img style="width: 28px;" src="~/images/loader.gif" id="loaderImg" hidden></h2>
    </div>
    <hr />
    <form asp-controller="GrpProdutos" asp-action="ConsultarGrpProdutosPost" method="post" onsubmit="disableObj(ConsultarBtn);showObj(loaderImg)">
        <table id="formularios">
            <tr>
                <th>
                    <label for="id">Código</label>
                    <br />
                    <input class="input input-sm" id="id" name="id" type="number" />
                </th>
                <th>
                    <label for="descricao">Descrição</label>
                    <br />
                    <input class="input input-sm" id="descricao" name="descricao" type="text" />
                </th>
            </tr>
            <tr>
        </table>
        <table id="formularios">
            <tr>
                <th>
                    <button class="btn btn-default" id="ConsultarBtn" type="submit">Consultar</button>
                </th>
            </tr>
        </table>
    </form>
    <hr />
    <table id="consultas">
        <tr>
            <th width=50>Código</th>
            <th width=300>Nome</th>
            <th width=300>Icone</th>
        </tr>
        @foreach (var grpproduto in ViewBag.grpprodutos)
        {
            <tr>
                <td>@grpproduto.Id</td>
                <td>@grpproduto.Descricao</td>
                <td>
                    <img src="@grpproduto.Icone" />
                </td>
            </tr>
        }
    </table>
    @if (ViewBag.responseStatusCode == "OK")
    {
        @if (ViewBag.erro)
        {
            <h4 style="color : red">@ViewBag.mensagem</h4>
        }
        else
        {
            @if (ViewBag.grpprodutos.Count == 0)
            {
                <h5 style="color : red">Nenhum registro encontrado.</h5>
            }
        }

    }
    else
    {
        <h4 style="color : red"> @ViewBag.responseStatusCode </h4>
    }
</div>