visual_studio/rift_estacionamento/rift_estacionamento/rift_estacionamento/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using rift_estacionamento.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace rift_estacionamento.Controllers
{
   

    public class AuthController : Controller
    {
        private static string mensagem = "";

        public IActionResult Login()
        {
            ViewData["Message"] = mensagem;
            return View();
        }
        
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(string login, string senha)
        {
            mensagem = "";

            ReClienteHttp httpClient = ReClienteHttp.Instance;

            var usuario_senha = new Dictionary<string, string>
            {
                { "login", login},
                { "senha", senha }
            };

            var request = new HttpRequestMessage();
            request.Content = new FormUrlEncodedContent(usuario_senha);

            var response = new HttpResponseMessage();
            try
            {
                response = httpClient.client.PostAsync("api/login_usuario", request.Content).Result;
            }
            catch (Exception e)
            {
                mensagem = "Erro crítico. " + e.Message;
                return RedirectToAction(nameof(Login));
            }

            string data = await response.Content.ReadAsStringAsync();

            Token token = new Token();
            if (response.IsSuccessStatusCode)
            {
                token = JsonConvert.DeserializeObject<Token>(data);
            }
            else
            {
                mensagem = "Erro crítico." + response.StatusCode.ToString();
                return RedirectToAction(nameof(Login));
            }

            if (!token.Item2.Erro && token.Item1.Token != "")
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, login, ClaimValueTypes.String)
                };

                var userIdentity = new ClaimsIdentity(claims, Constantes.RIFT_ESTACIONAMENTO + "SecureLogin");
                var userPrincipal = new ClaimsPrincipal(userIdentity);

                await HttpContext.SignInAsync(Constantes.RIFT_ESTACIONAMENTO,
                    userPrincipal,
                    new AuthenticationProperties
                    {
                        IsPersistent = false,
                        AllowRefresh = false
                    });

                Utils.ClearAllCookies(HttpContext);

                Utils.SetCookie(Constantes.LOGADO, "true", HttpContext);
                Utils.SetCookie(Constantes.TOKEN_USUARIO, token.Item1.Token, HttpContext);
                Utils.SetCookie(Constantes.ID_USUARIO, token.Item1.Id, HttpContext);

                return RedirectToAction("Index", "Home");
            }

            mensagem = token.Item2.Mensagem;

            return RedirectToAction(nameof(Login));

        }

        public async Task<IActionResult> Logout()
        {
            Utils.ClearAllCookies(HttpContext);
            await HttpContext.SignOutAsync();
            return RedirectToAction(nameof(Login));
        }
    }
}

visual_studio/rift_estacionamento/rift_estacionamento/rift_estacionamento/Controllers/PessoasFisicasController.cs
using rift_estacionamento.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using System;

namespace rift_estacionamento.Controllers
{
    [Authorize]
    public class PessoasFisicasController : Controller
    {
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult FonesPessoaFisica(int id_pessoa_fisica, string nome, string responseStr, string responseStrFonePF, string responseStatusCode)
        {

            FonePessoaFisica _fones_pessoa_fisica = new FonePessoaFisica();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                var settings = new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore
                };
                _fones_pessoa_fisica = JsonConvert.DeserializeObject<FonePessoaFisica>(responseStr, settings);
            }

            ProcessarRegistro _processarregistro = new ProcessarRegistro();

            if (!string.IsNullOrWhiteSpace(responseStrFonePF))
            {
                _processarregistro = JsonConvert.DeserializeObject<ProcessarRegistro>(responseStrFonePF);
            }


            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.id_pessoa_fisica = id_pessoa_fisica;
            ViewBag.nome = nome;

            ViewBag.fones_pf = (_fones_pessoa_fisica == null || _fones_pessoa_fisica.Item1 == null) ? new List<FonePessoaFisica.Dados>() : _fones_pessoa_fisica.Item1;

            ViewBag.erro = (_processarregistro == null || _processarregistro.Item2 == null ? false : _processarregistro.Item2.Erro);
            ViewBag.linhasafetadas = (_processarregistro == null || _processarregistro.Item1 == null ? -1 : _processarregistro.Item1.Linhasafetadas);
            ViewBag.mensagem = (_processarregistro == null || _processarregistro.Item2 == null ? "" : _processarregistro.Item2.Mensagem);
            ViewBag.responseStatusCode = responseStatusCode;

            return View("FonesPessoaFisica");
        }

        public IActionResult EmailsPessoaFisica(int id_pessoa_fisica, string nome, string responseStr, string responseStrEmailPF, string responseStatusCode)
        {

            EmailPessoaFisica _emails_pessoa_fisica = new EmailPessoaFisica();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                var settings = new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore
                };
                _emails_pessoa_fisica = JsonConvert.DeserializeObject<EmailPessoaFisica>(responseStr, settings);
            }

            ProcessarRegistro _processarregistro = new ProcessarRegistro();

            if (!string.IsNullOrWhiteSpace(responseStrEmailPF))
            {
                _processarregistro = JsonConvert.DeserializeObject<ProcessarRegistro>(responseStrEmailPF);
            }


            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.id_pessoa_fisica = id_pessoa_fisica;
            ViewBag.nome = nome;

            ViewBag.emails_pf = (_emails_pessoa_fisica == null || _emails_pessoa_fisica.Item1 == null) ? new List<EmailPessoaFisica.Dados>() : _emails_pessoa_fisica.Item1;

            ViewBag.erro = (_processarregistro == null || _processarregistro.Item2 == null ? false : _processarregistro.Item2.Erro);
            ViewBag.linhasafetadas = (_processarregistro == null || _processarregistro.Item1 == null ? -1 : _processarregistro.Item1.Linhasafetadas);
            ViewBag.mensagem = (_processarregistro == null || _processarregistro.Item2 == null ? "" : _processarregistro.Item2.Mensagem);
            ViewBag.responseStatusCode = responseStatusCode;

            return View("EmailsPessoaFisica");
        }

        public IActionResult EditarPessoasFisicas(int id, string responseStr, string responseStatusCode)
        {

            ProcessarRegistro _processarregistro = new ProcessarRegistro();
            PessoaFisica _pessoafisica = new PessoaFisica();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                if (id == 0)
                {
                    _processarregistro = JsonConvert.DeserializeObject<ProcessarRegistro>(responseStr);
                }
                else
                {
                    _pessoafisica = JsonConvert.DeserializeObject<PessoaFisica>(responseStr);
                }
            }


            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.id = id;
            ViewBag.cpf = (_pessoafisica == null || _pessoafisica.Item1 == null) ? "" : _pessoafisica.Item1[0].Cpf;
            ViewBag.nome = (_pessoafisica == null || _pessoafisica.Item1 == null) ? "" : _pessoafisica.Item1[0].Nome;
            ViewBag.sexo = (_pessoafisica == null || _pessoafisica.Item1 == null) ? "" : _pessoafisica.Item1[0].Sexo;
            ViewBag.data_nasc = (_pessoafisica == null || _pessoafisica.Item1 == null) ? "" : _pessoafisica.Item1[0].Data_nasc.ToString("yyyy-MM-dd");
            ViewBag.rg = (_pessoafisica == null || _pessoafisica.Item1 == null) ? "" : _pessoafisica.Item1[0].Rg;
            ViewBag.endereco = (_pessoafisica == null || _pessoafisica.Item1 == null) ? "" : _pessoafisica.Item1[0].Endereco;

            ViewBag.erro = (_processarregistro == null || _processarregistro.Item2 == null ? false : _processarregistro.Item2.Erro);
            ViewBag.linhasafetadas = (_processarregistro == null || _processarregistro.Item1 == null ? -1 : _processarregistro.Item1.Linhasafetadas);
            ViewBag.mensagem = (_processarregistro == null || _processarregistro.Item2 == null ? "" : _processarregistro.Item2.Mensagem);
            ViewBag.responseStatusCode = responseStatusCode;

            return View("EditarPessoasFisicas");
        }


        public IActionResult IncluirPessoasFisicas(string responseStr, string responseStatusCode, string inclusao_pessoafisica)
        {
            NovoRegistro _novapessofisica = new NovoRegistro();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                _novapessofisica = JsonConvert.DeserializeObject<NovoRegistro>(responseStr);
            }

            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.id = (_novapessofisica == null || _novapessofisica.Item1 == null ? 0 : _novapessofisica.Item1.Id);
            ViewBag.erro = (_novapessofisica == null  || _novapessofisica.Item2 == null ? false : _novapessofisica.Item2.Erro);
            ViewBag.mensagem = (_novapessofisica == null || _novapessofisica.Item2 == null ? "" : _novapessofisica.Item2.Mensagem);
            ViewBag.responseStatusCode = responseStatusCode;

            if (ViewBag.erro)
            {
                Dictionary<string, string> inclusao = JsonConvert.DeserializeObject<Dictionary<string, string>>(inclusao_pessoafisica);
                ViewBag.cpf = inclusao["cpf"];
                ViewBag.nome = inclusao["nome"];
                ViewBag.sexo = inclusao["sexo"];
                ViewBag.data_nasc = inclusao["data_nasc"];
                ViewBag.rg = inclusao["rg"];
                ViewBag.endereco = inclusao["endereco"];
            }

            return View("IncluirPessoasFisicas");
        }

        public IActionResult ConsultarPessoasFisicas(string responseStr, string responseStrExc, string responseStatusCode)
        {
            PessoaFisica _pessoafisica = new PessoaFisica();

            if (!string.IsNullOrWhiteSpace(responseStr))
            {
                _pessoafisica = JsonConvert.DeserializeObject<PessoaFisica>(responseStr);
                ViewBag.erro = (_pessoafisica == null || _pessoafisica.Item2 == null ? false : _pessoafisica.Item2.Erro);
                ViewBag.mensagem = (_pessoafisica == null || _pessoafisica.Item2 == null ? "" : _pessoafisica.Item2.Mensagem);
                ViewBag.excluindo = false;
            }

            if (!string.IsNullOrWhiteSpace(responseStrExc))
            {
                ProcessarRegistro _proc = new ProcessarRegistro();
                _proc = JsonConvert.DeserializeObject<ProcessarRegistro>(responseStrExc);
                ViewBag.erro = (_proc == null || _proc.Item2 == null ? false : _proc.Item2.Erro);
                ViewBag.mensagem = (_proc == null || _proc.Item2 == null ? "" : _proc.Item2.Mensagem);
                ViewBag.excluindo = true;
            }

          
            Utils.formataCabecalho(ViewBag, Request);
            ViewBag.pessoasfisicas = (_pessoafisica == null || _pessoafisica.Item1 == null) ? new List<PessoaFisica.Dados>() : _pessoafisica.Item1;

            ViewBag.responseStatusCode = responseStatusCode;

            return View("ConsultarPessoasFisicas");
        }


        [HttpPost]
        public async Task<IActionResult>IncluirPessoasFisicasPost( string cpf, string nome, string sexo, DateTime data_nasc, string rg, string endereco)
        {
            ReClienteHttp httpClient = ReClienteHttp.Instance;

            var novo_pessoafisica = new Dictionary<string, string>
            {
                { "cpf", cpf },
                { "nome", nome },
                { "sexo", sexo },
                { "data_nasc", data_nasc.ToString("dd/MM/yyyy") },
                { "rg", rg },
                { "endereco", endereco },
                { "token", Request.Cookies[Constantes.TOKEN_USUARIO] }
            };

            var request = new HttpRequestMessage();
            request.Content = new FormUrlEncodedContent(novo_pessoafisica);

            var response = httpClient.client.PostAsync("api/incluir_pessoa_fisica", request.Content).Result;

visual_studio/rift_estacionamento/rift_estacionamento/rift_estacionamento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - rift_estacionamento</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <table style="width:100%">
            <tr>
                <td width="20%">
                    <img style="margin: 5px 5px; width: 56px;" src="~/images/rift_logo.png"> <h style="color:white"> Rift Estacionamento </h>
                </td>
                <td td width="60%">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">

                                @if (ViewBag.logado == true)
                                {

                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pessoa Física <span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a asp-area="" asp-controller="PessoasFisicas" asp-action="IncluirPessoasFisicas">Cadastro</a></li>
                                            <li><a asp-area="" asp-controller="PessoasFisicas" asp-action="ConsultarPessoasFisicas">Consulta</a></li>
                                        </ul>
                                    </li>

                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pessoa Jurídica <span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a asp-area="" asp-controller="PessoasJuridicas" asp-action="IncluirPessoasJuridicas">Cadastro</a></li>
                                            <li><a asp-area="" asp-controller="PessoasJuridicas" asp-action="ConsultarPessoasJuridicas">Consulta</a></li>
                                        </ul>
                                    </li>

                                    <li><a asp-area="" asp-controller="Auth" asp-action="Logout">Sair</a></li>
                                }

                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

    <script type="text/javascript" src="~/lib/jquery-mask/masked_input_1.4.1.js"></script>

    <script>
        function disableObj(obj) {
            obj.disabled = true;
        }

        function unabledObj(obj) {
            obj.disabled = false;
        }

        function showObj(obj) {
            obj.hidden = null;
        }

        function Confirmar(mensagem) {
            if (confirm(mensagem))
                return true;
            else
                return false;
        }

        function formatarMoeda(obj) {
            var valor = obj.value;

            if (valor == '') {
                valor = '0';
            }

            valor = valor + '';
            valor = parseInt(valor.replace(/[\D]+/g, ''));
            valor = valor + '';
            valor = valor.replace(/([0-9]{2})$/g, ",$1");

            obj.value = valor;

        }
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            MaskedInput({
                elm: document.getElementById('cpf'),
                format: '___.___.___-__',
                separator: '-.'
            });

            MaskedInput({
                elm: document.getElementById('cnpj'),
                format: '__.___.___/____-__',
                separator: '/-.'
            });

             MaskedInput({
                elm: document.getElementById('fone'),
                allowed: ' 0123456789',
                format: '(__) _____-____',
                separator: '()- '
            });


        });
    </script>

</body>
</html>